import * as React from 'react'
import type { DeviceProps } from '../_core/device'
import { applyStyle, youtubeEmbedUrl } from '../_core/preview'

export const VideoDevice: React.FC<DeviceProps> = ({ config, theme, style, onAdvance }) => {
  const cfg = config || {}
  const buttonStyle: React.CSSProperties = { backgroundColor: theme.primary, borderRadius: theme.radius, color: 'white' }
  return <div className="min-w-0 w-full max-w-full" style={{ ...applyStyle(style || {}), maxWidth: '100%', minWidth: 0 }}>{cfg.url ? <div className="aspect-video w-full min-w-0 max-w-full overflow-hidden bg-black" style={{ borderRadius: theme.radius, maxWidth: '100%' }}><iframe src={youtubeEmbedUrl(cfg.url)} title={cfg.title || 'Video'} className="h-full w-full max-w-full" style={{ border: 0, display: 'block', maxWidth: '100%' }} allow="autoplay; encrypted-media" allowFullScreen loading="lazy" /></div> : cfg.src ? <video src={cfg.src} poster={cfg.poster} autoPlay={Boolean(cfg.autoplay)} loop={Boolean(cfg.loop)} controls={cfg.controls !== false} playsInline preload="metadata" className="block w-full min-w-0 max-w-full" style={{ borderRadius: theme.radius, maxWidth: '100%', height: 'auto' }} /> : <div className="min-w-0 max-w-full break-words border p-3 text-xs" style={{ color: theme.accent, borderColor: theme.accent, backgroundColor: theme.accent + '14', borderRadius: theme.radius, overflowWrap: 'break-word' }}>No video source</div>}{cfg.blockOwnsExit && (cfg.showWatchedButton || cfg.showSkipButton) && <div className="mt-3 flex min-w-0 max-w-full flex-wrap gap-2">{cfg.showWatchedButton && <button type="button" onClick={e => { e.stopPropagation(); onAdvance('watched') }} className="min-h-[44px] min-w-0 flex-1 basis-36 break-words px-3 py-2 text-xs text-white sm:text-sm" style={{ ...buttonStyle, maxWidth: '100%' }}>{cfg.watchedLabel || 'I watched it'}</button>}{cfg.showSkipButton && <button type="button" onClick={e => { e.stopPropagation(); onAdvance('skipped') }} className="min-h-[44px] min-w-0 flex-1 basis-36 break-words border px-3 py-2 text-xs opacity-70 sm:text-sm" style={{ borderRadius: theme.radius, maxWidth: '100%' }}>{cfg.skipLabel || 'Skip'}</button>}</div>}</div>
}
export default VideoDevice
