import * as React from 'react'
import type { StyleConfigProps } from '../_core/config'
import { ColorFieldWithHex, TextField, SelectField, SegmentedControl, NumberField } from '../_core/styleWidgets'
export const TriggerStyleConfig: React.FC<StyleConfigProps> = ({ style, onChange, theme }) => {
  return <div className="space-y-4"><ColorFieldWithHex label="Background" value={style.backgroundColor} onChange={v => onChange('backgroundColor', v)} /><ColorFieldWithHex label="Text" value={style.foregroundColor} onChange={v => onChange('foregroundColor', v)} /><ColorFieldWithHex label="Border" value={style.borderColor} onChange={v => onChange('borderColor', v)} />
<SelectField label="Font" value={style.fontFamily} onChange={v => onChange('fontFamily', v)} options={[{value:'Inter',label:'Inter'},{value:'system-ui',label:'System'},{value:'Georgia',label:'Georgia'}]} /><SelectField label="Weight" value={style.fontWeight} onChange={v => onChange('fontWeight', v)} options={[{value:'300',label:'Light'},{value:'400',label:'Regular'},{value:'600',label:'Semibold'},{value:'700',label:'Bold'}]} /><TextField label="Font size" value={style.fontSize} onChange={v => onChange('fontSize', v)} placeholder="14px" /><SegmentedControl label="Align" value={style.textAlign} onChange={v => onChange('textAlign', v)} options={[{value:'left',label:'Left'},{value:'center',label:'Center'},{value:'right',label:'Right'}]} />
<TextField label="Radius" value={style.borderRadius} onChange={v => onChange('borderRadius', v)} placeholder="8px" /><SelectField label="Style" value={style.borderStyle} onChange={v => onChange('borderStyle', v)} options={[{value:'solid',label:'Solid'},{value:'dashed',label:'Dashed'},{value:'none',label:'None'}]} /><TextField label="Width" value={style.borderWidth} onChange={v => onChange('borderWidth', v)} placeholder="1px" />
<SelectField label="Shadow" value={(style as any).boxShadow} onChange={v => onChange('boxShadow' as any, v)} options={[{value:'none',label:'None'},{value:'0 4px 12px rgba(15,23,42,0.10)',label:'Medium'},{value:'0 12px 32px rgba(15,23,42,0.16)',label:'Elevated'}]} /><NumberField label="Opacity" value={style.opacity} onChange={v => onChange('opacity', v)} min={0} max={1} step={0.05} placeholder="1" />
</div>
}
export default TriggerStyleConfig
