import * as React from 'react'
import type { DeviceProps } from '../_core/device'

export const HeroSectionDevice: React.FC<DeviceProps> = ({ config, theme, onAdvance }) => {
  const cfg = config || {}
  const sideImage = cfg.imagePosition === 'left'
  return <div className={`flex w-full min-w-0 max-w-full flex-col items-center gap-4 px-4 py-8 text-center sm:gap-5 sm:px-6 sm:py-10 lg:px-8 ${sideImage ? 'md:flex-row-reverse md:items-center md:gap-6 md:text-left lg:gap-8' : ''}`} style={{ maxWidth: '100%', boxSizing: 'border-box' }}>{cfg.badge && <span className="inline-block min-w-0 max-w-full break-words px-3 py-1 text-xs font-medium" style={{ backgroundColor: theme.primary + '20', color: theme.primary, borderRadius: theme.radius, overflowWrap: 'break-word' }}>{cfg.badge}</span>}<div className="min-w-0 max-w-full flex-1">{cfg.headline && <h2 className="mb-2 min-w-0 break-words text-xl font-bold sm:text-2xl lg:text-3xl" style={{ fontFamily: theme.font, lineHeight: 1.25, overflowWrap: 'break-word', wordBreak: 'break-word', textWrap: 'balance' } as React.CSSProperties}>{cfg.headline}</h2>}{cfg.subheadline && <p className="mx-auto mb-4 min-w-0 max-w-xl break-words text-sm opacity-80 sm:text-base" style={{ fontFamily: theme.font, lineHeight: 1.6, overflowWrap: 'break-word' }}>{cfg.subheadline}</p>}{cfg.image && <img src={cfg.image} alt="" loading="lazy" decoding="async" className={`mx-auto mb-4 h-auto max-h-[260px] w-full max-w-full object-cover sm:max-h-[360px] ${sideImage ? 'md:mb-0 md:max-h-[420px]' : 'md:max-w-2xl'}`} style={{ borderRadius: theme.radius, maxWidth: '100%' }} />}{cfg.blockOwnsExit && <div className="flex w-full min-w-0 max-w-full flex-col gap-2 min-[420px]:flex-row min-[420px]:flex-wrap min-[420px]:justify-center">{(cfg.ctas || []).map((cta: any, i: number) => <button key={i} type="button" className="min-h-[44px] w-full min-w-0 max-w-full flex-1 break-words px-4 py-2 text-sm font-medium min-[420px]:w-auto sm:text-base" style={{ backgroundColor: i === 0 ? theme.primary : 'transparent', border: i > 0 ? `2px solid ${theme.primary}` : 'none', color: i > 0 ? theme.primary : 'white', borderRadius: theme.radius, overflowWrap: 'break-word', lineHeight: 1.4 }} onClick={e => { e.stopPropagation(); onAdvance(cta.handle || `cta-${i}`) }}>{cta.label}</button>)}</div>}</div></div>
}
export default HeroSectionDevice
