[alembic]
script_location = alembic
sqlalchemy.url = postgresql://journeo:journeo_dev@localhost:5432/journeo
[loggers]
keys = root
[handlers]
keys = console
[logger_root]
level = WARN
handlers = console
