import * as React from 'react'
import type { DeviceProps } from '../_core/device'

export const CardDevice: React.FC<DeviceProps> = ({ config, theme, onAdvance }) => {
  const cfg = config || {}
  const horizontal = cfg.layout === 'horizontal'
  return <div className={`w-full min-w-0 max-w-full overflow-hidden ${horizontal ? 'flex flex-col sm:flex-row' : 'flex flex-col'}`} style={{ maxWidth: '100%' }}>{cfg.image?.src && <img src={cfg.image.src} alt={cfg.image.alt || ''} loading="lazy" decoding="async" className={horizontal ? 'h-40 w-full min-w-0 object-cover sm:h-auto sm:w-1/3 sm:min-w-0' : 'h-auto w-full min-w-0 max-w-full object-cover'} style={{ borderRadius: horizontal ? 0 : `${theme.radius}px ${theme.radius}px 0 0`, aspectRatio: horizontal ? undefined : cfg.image.aspectRatio || '16/9', objectFit: 'cover', objectPosition: cfg.image.position || 'center', maxWidth: '100%' }} />}<div className="min-w-0 max-w-full flex-1 p-4 sm:p-5">{cfg.badge && <span className="mb-2 inline-block min-w-0 max-w-full break-words rounded px-2 py-0.5 text-xs font-medium" style={{ backgroundColor: theme.primary + '20', color: theme.primary, overflowWrap: 'break-word' }}>{cfg.badge}</span>}{cfg.title && <h3 className="mb-1 min-w-0 break-words font-semibold" style={{ fontFamily: theme.font, overflowWrap: 'break-word', wordBreak: 'break-word', lineHeight: 1.35 }}>{cfg.title}</h3>}{cfg.description && <p className="mb-3 min-w-0 break-words text-sm leading-relaxed opacity-80" style={{ fontFamily: theme.font, overflowWrap: 'break-word', wordBreak: 'break-word' }}>{cfg.description}</p>}{cfg.blockOwnsExit && <div className="flex min-w-0 max-w-full flex-wrap gap-x-3 gap-y-2">{cfg.actions?.map((action: any, i: number) => <button key={i} type="button" className="min-h-[44px] min-w-0 max-w-full break-words py-1 text-left text-sm font-medium" style={{ color: theme.primary, overflowWrap: 'break-word' }} onClick={e => { e.stopPropagation(); onAdvance(action.handle || `action-${i}`) }}>{action.label}</button>)}</div>}</div></div>
}
export default CardDevice
