import * as React from 'react'
import type { StyleConfigProps } from '../_core/config'
import { ColorFieldWithHex, TextField, SelectField, SegmentedControl, NumberField } from '../_core/styleWidgets'
export const AskAiStyleConfig: React.FC<StyleConfigProps> = ({ style, onChange }) => {
  return <div className="space-y-4"><ColorFieldWithHex label="Background" value={style.backgroundColor} onChange={v => onChange('backgroundColor', v)} /><ColorFieldWithHex label="Text" value={style.foregroundColor} onChange={v => onChange('foregroundColor', v)} /><ColorFieldWithHex label="Border" value={style.borderColor} onChange={v => onChange('borderColor', v)} />
<SelectField label="Font" value={style.fontFamily} onChange={v => onChange('fontFamily', v)} options={[{value:'Inter',label:'Inter'},{value:'system-ui',label:'System'},{value:'Georgia',label:'Georgia'}]} /><TextField label="Font size" value={style.fontSize} onChange={v => onChange('fontSize', v)} placeholder="14px" /><SegmentedControl label="Align" value={style.textAlign} onChange={v => onChange('textAlign', v)} options={[{value:'left',label:'Left'},{value:'center',label:'Center'},{value:'right',label:'Right'}]} />
<TextField label="Radius" value={style.borderRadius} onChange={v => onChange('borderRadius', v)} placeholder="12px" /><TextField label="Padding" value={style.padding} onChange={v => onChange('padding', v)} placeholder="12px" />
<SelectField label="Shadow" value={(style as any).boxShadow} onChange={v => onChange('boxShadow' as any, v)} options={[{value:'none',label:'None'},{value:'0 4px 12px rgba(15,23,42,0.10)',label:'Medium'},{value:'0 12px 32px rgba(15,23,42,0.16)',label:'Elevated'}]} /><NumberField label="Opacity" value={style.opacity} onChange={v => onChange('opacity', v)} min={0} max={1} step={0.05} placeholder="1" />
<div className="space-y-3 rounded-none border bg-muted/20 p-3"><div className="text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">Fixed placement</div><SelectField label="Position" value={style.position} onChange={v => onChange('position', v)} options={[{value:'fixed',label:'Fixed'},{value:'absolute',label:'Absolute'},{value:'relative',label:'Relative'},{value:'sticky',label:'Sticky'},{value:'static',label:'Static'}]} /><div className="grid grid-cols-2 gap-2"><TextField label="Top" value={style.top} onChange={v => onChange('top', v)} placeholder="auto" /><TextField label="Right" value={style.right} onChange={v => onChange('right', v)} placeholder="16px" /><TextField label="Bottom" value={style.bottom} onChange={v => onChange('bottom', v)} placeholder="16px" /><TextField label="Left" value={style.left} onChange={v => onChange('left', v)} placeholder="auto" /></div><div className="grid grid-cols-2 gap-2"><TextField label="Width" value={style.width} onChange={v => onChange('width', v)} placeholder="auto · ≤100%" /><NumberField label="Z-index" value={style.zIndex} onChange={v => onChange('zIndex', v)} step={1} placeholder="20" /></div></div>
</div>
}
export default AskAiStyleConfig
